name: 'save-pr-number'
description: 'Saves the current PR number as artifact'
inputs:
  platform-name:
    description: "Name of the target platform"
    required: true
runs:
  using: "composite"
  steps:
      - name: Save PR number
        shell: bash
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.number }}" > ./pr_number

      - name: Upload pr_number
        uses: actions/upload-artifact@v4
        with:
          name: pr-number-${{ inputs.platform-name }}
          path: ./pr_number
